In [1]:
import numpy as np
from numpy import pi, cos, sin, linspace, meshgrid
import pyvista as pv
from itkwidgets import view

In [2]:
def x_(u, v):
    x = -2 + 2*cos(v) - cos(u)
    x[v<3*pi] = -2 + (2 + cos(u[v<3*pi]))*cos(v[v<3*pi])
    x[v<2*pi] = cos(u[v<2*pi])*(2.5 - 1.5*cos(v[v<2*pi]))
    return x

def y_(u, v):
    y = sin(u)
    y[v<2*pi] = sin(u[v<2*pi])*(2.5 - 1.5*cos(v[v<2*pi]))
    return y

def z_(u, v):
    z = -3*v + 12*pi
    z[v<3*pi] = (2 + cos(u[v<3*pi]))*sin(v[v<3*pi]) + 3*pi
    z[v<2*pi] = 3*v[v<2*pi] - 3*pi
    z[v<pi] = -2.5*sin(v[v<pi])
    return -z

 
u = linspace(pi, 2*pi, 10)
v = linspace(0, 4*pi, 38)
u, v = meshgrid(u, v)

x = x_(u, v)
y = y_(u, v)
z = z_(u, v)

In [7]:
grid = pv.StructuredGrid(x, y, z)
grid["z"] = z.T.ravel()
grid["y"] = y.T.ravel()
view(geometries=grid, ,cmap="Plasma (matplotlib)")

TraitError: The 'point_sets' trait of a Viewer instance must be Point set representation for rendering geometry in vtk.js., but a value of array([ 1.22464680e-16,  1.32957923e-16,  1.63238850e-16,  2.09848014e-16,
        2.67460546e-16,  3.29494495e-16,  3.88862786e-16,  4.38782883e-16,
        4.73551658e-16,  4.89196949e-16,  4.83931358e-16,  4.58356453e-16,
        4.15394042e-16,  3.59952370e-16,  2.98365377e-16,  2.37669076e-16,
        1.84797722e-16,  1.45791609e-16,  1.25106994e-16,  1.22464680e-16,
        1.22464680e-16,  1.22464680e-16,  1.22464680e-16,  1.22464680e-16,
        1.22464680e-16,  1.22464680e-16,  1.22464680e-16,  1.22464680e-16,
        1.22464680e-16,  1.22464680e-16,  1.22464680e-16,  1.22464680e-16,
        1.22464680e-16,  1.22464680e-16,  1.22464680e-16,  1.22464680e-16,
        1.22464680e-16,  1.22464680e-16, -3.42020143e-01, -3.71325740e-01,
       -4.55894508e-01, -5.86064880e-01, -7.46965527e-01, -9.20214338e-01,
       -1.08601848e+00, -1.22543565e+00, -1.32253811e+00, -1.36623238e+00,
       -1.35152660e+00, -1.28010084e+00, -1.16011514e+00, -1.00527729e+00,
       -8.33276739e-01, -6.63763719e-01, -5.16104263e-01, -4.07167740e-01,
       -3.49399616e-01, -3.42020143e-01, -3.42020143e-01, -3.42020143e-01,
       -3.42020143e-01, -3.42020143e-01, -3.42020143e-01, -3.42020143e-01,
       -3.42020143e-01, -3.42020143e-01, -3.42020143e-01, -3.42020143e-01,
       -3.42020143e-01, -3.42020143e-01, -3.42020143e-01, -3.42020143e-01,
       -3.42020143e-01, -3.42020143e-01, -3.42020143e-01, -3.42020143e-01,
       -6.42787610e-01, -6.97864115e-01, -8.56801410e-01, -1.10144169e+00,
       -1.40383599e+00, -1.72943725e+00, -2.04104711e+00, -2.30306567e+00,
       -2.48555860e+00, -2.56767696e+00, -2.54003915e+00, -2.40580263e+00,
       -2.18030328e+00, -1.88930330e+00, -1.56604800e+00, -1.24746774e+00,
       -9.69958735e-01, -7.65225042e-01, -6.56656482e-01, -6.42787610e-01,
       -6.42787610e-01, -6.42787610e-01, -6.42787610e-01, -6.42787610e-01,
       -6.42787610e-01, -6.42787610e-01, -6.42787610e-01, -6.42787610e-01,
       -6.42787610e-01, -6.42787610e-01, -6.42787610e-01, -6.42787610e-01,
       -6.42787610e-01, -6.42787610e-01, -6.42787610e-01, -6.42787610e-01,
       -6.42787610e-01, -6.42787610e-01, -8.66025404e-01, -9.40229779e-01,
       -1.15436542e+00, -1.48396837e+00, -1.89138311e+00, -2.33006450e+00,
       -2.74989533e+00, -3.10291199e+00, -3.34878404e+00, -3.45942182e+00,
       -3.42218548e+00, -3.24132911e+00, -2.93751466e+00, -2.54545145e+00,
       -2.10993077e+00, -1.68070874e+00, -1.30682187e+00, -1.03098491e+00,
       -8.84710884e-01, -8.66025404e-01, -8.66025404e-01, -8.66025404e-01,
       -8.66025404e-01, -8.66025404e-01, -8.66025404e-01, -8.66025404e-01,
       -8.66025404e-01, -8.66025404e-01, -8.66025404e-01, -8.66025404e-01,
       -8.66025404e-01, -8.66025404e-01, -8.66025404e-01, -8.66025404e-01,
       -8.66025404e-01, -8.66025404e-01, -8.66025404e-01, -8.66025404e-01,
       -9.84807753e-01, -1.06918985e+00, -1.31269592e+00, -1.68750657e+00,
       -2.15080151e+00, -2.64965158e+00, -3.12706559e+00, -3.52850132e+00,
       -3.80809671e+00, -3.93390934e+00, -3.89156575e+00, -3.68590347e+00,
       -3.34041843e+00, -2.89458059e+00, -2.39932474e+00, -1.91123146e+00,
       -1.48606300e+00, -1.17239278e+00, -1.00605610e+00, -9.84807753e-01,
       -9.84807753e-01, -9.84807753e-01, -9.84807753e-01, -9.84807753e-01,
       -9.84807753e-01, -9.84807753e-01, -9.84807753e-01, -9.84807753e-01,
       -9.84807753e-01, -9.84807753e-01, -9.84807753e-01, -9.84807753e-01,
       -9.84807753e-01, -9.84807753e-01, -9.84807753e-01, -9.84807753e-01,
       -9.84807753e-01, -9.84807753e-01, -9.84807753e-01, -1.06918985e+00,
       -1.31269592e+00, -1.68750657e+00, -2.15080151e+00, -2.64965158e+00,
       -3.12706559e+00, -3.52850132e+00, -3.80809671e+00, -3.93390934e+00,
       -3.89156575e+00, -3.68590347e+00, -3.34041843e+00, -2.89458059e+00,
       -2.39932474e+00, -1.91123146e+00, -1.48606300e+00, -1.17239278e+00,
       -1.00605610e+00, -9.84807753e-01, -9.84807753e-01, -9.84807753e-01,
       -9.84807753e-01, -9.84807753e-01, -9.84807753e-01, -9.84807753e-01,
       -9.84807753e-01, -9.84807753e-01, -9.84807753e-01, -9.84807753e-01,
       -9.84807753e-01, -9.84807753e-01, -9.84807753e-01, -9.84807753e-01,
       -9.84807753e-01, -9.84807753e-01, -9.84807753e-01, -9.84807753e-01,
       -8.66025404e-01, -9.40229779e-01, -1.15436542e+00, -1.48396837e+00,
       -1.89138311e+00, -2.33006450e+00, -2.74989533e+00, -3.10291199e+00,
       -3.34878404e+00, -3.45942182e+00, -3.42218548e+00, -3.24132911e+00,
       -2.93751466e+00, -2.54545145e+00, -2.10993077e+00, -1.68070874e+00,
       -1.30682187e+00, -1.03098491e+00, -8.84710884e-01, -8.66025404e-01,
       -8.66025404e-01, -8.66025404e-01, -8.66025404e-01, -8.66025404e-01,
       -8.66025404e-01, -8.66025404e-01, -8.66025404e-01, -8.66025404e-01,
       -8.66025404e-01, -8.66025404e-01, -8.66025404e-01, -8.66025404e-01,
       -8.66025404e-01, -8.66025404e-01, -8.66025404e-01, -8.66025404e-01,
       -8.66025404e-01, -8.66025404e-01, -6.42787610e-01, -6.97864115e-01,
       -8.56801410e-01, -1.10144169e+00, -1.40383599e+00, -1.72943725e+00,
       -2.04104711e+00, -2.30306567e+00, -2.48555860e+00, -2.56767696e+00,
       -2.54003915e+00, -2.40580263e+00, -2.18030328e+00, -1.88930330e+00,
       -1.56604800e+00, -1.24746774e+00, -9.69958735e-01, -7.65225042e-01,
       -6.56656482e-01, -6.42787610e-01, -6.42787610e-01, -6.42787610e-01,
       -6.42787610e-01, -6.42787610e-01, -6.42787610e-01, -6.42787610e-01,
       -6.42787610e-01, -6.42787610e-01, -6.42787610e-01, -6.42787610e-01,
       -6.42787610e-01, -6.42787610e-01, -6.42787610e-01, -6.42787610e-01,
       -6.42787610e-01, -6.42787610e-01, -6.42787610e-01, -6.42787610e-01,
       -3.42020143e-01, -3.71325740e-01, -4.55894508e-01, -5.86064880e-01,
       -7.46965527e-01, -9.20214338e-01, -1.08601848e+00, -1.22543565e+00,
       -1.32253811e+00, -1.36623238e+00, -1.35152660e+00, -1.28010084e+00,
       -1.16011514e+00, -1.00527729e+00, -8.33276739e-01, -6.63763719e-01,
       -5.16104263e-01, -4.07167740e-01, -3.49399616e-01, -3.42020143e-01,
       -3.42020143e-01, -3.42020143e-01, -3.42020143e-01, -3.42020143e-01,
       -3.42020143e-01, -3.42020143e-01, -3.42020143e-01, -3.42020143e-01,
       -3.42020143e-01, -3.42020143e-01, -3.42020143e-01, -3.42020143e-01,
       -3.42020143e-01, -3.42020143e-01, -3.42020143e-01, -3.42020143e-01,
       -3.42020143e-01, -3.42020143e-01, -2.44929360e-16, -2.65915846e-16,
       -3.26477701e-16, -4.19696029e-16, -5.34921091e-16, -6.58988989e-16,
       -7.77725572e-16, -8.77565765e-16, -9.47103316e-16, -9.78393898e-16,
       -9.67862716e-16, -9.16712907e-16, -8.30788084e-16, -7.19904740e-16,
       -5.96730754e-16, -4.75338152e-16, -3.69595444e-16, -2.91583218e-16,
       -2.50213989e-16, -2.44929360e-16, -2.44929360e-16, -2.44929360e-16,
       -2.44929360e-16, -2.44929360e-16, -2.44929360e-16, -2.44929360e-16,
       -2.44929360e-16, -2.44929360e-16, -2.44929360e-16, -2.44929360e-16,
       -2.44929360e-16, -2.44929360e-16, -2.44929360e-16, -2.44929360e-16,
       -2.44929360e-16, -2.44929360e-16, -2.44929360e-16, -2.44929360e-16]) <class 'numpy.ndarray'> was specified.

In [8]:
view?


In [2]:
object = pv.read("test_cavity_new.vtk")

In [53]:
p = pv.Plotter()

In [3]:
view(geometries=object)

Viewer(geometries=[{'vtkClass': 'vtkPolyData', 'points': {'vtkClass': 'vtkPoints', 'name': '_points', 'numberO…

In [38]:
mesh.getElements()

(array([ 1,  2, 15], dtype=int32),
 [array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
         22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
         39, 40, 41, 42, 43, 44], dtype=uint64),
  array([ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
          58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
          71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
          97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
         110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
         123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
         149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
         175, 176, 177

In [38]:
mesh.getElements()

(array([ 1,  2, 15], dtype=int32),
 [array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
         22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
         39, 40, 41, 42, 43, 44], dtype=uint64),
  array([ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
          58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
          71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
          97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
         110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
         123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
         149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
         175, 176, 177

In [ ]:
T(x+h) = T(x) + ( T'(x) ) * h + ( T''(x)/2! ) * h**2

In [ ]:
import gmsh
import gmsh_api
gmsh.initialize()
gmsh.model.add("square")
gmsh.model.geo.addPoint(0, 0, 0, 0.1, 1)
gmsh.model.geo.addPoint(1, 0, 0, 0.1, 2)
gmsh.model.geo.addPoint(1, 1, 0, 0.1, 3)
gmsh.model.geo.addPoint(0, 1, 0, 0.1, 4)
gmsh.model.geo.addLine(1, 2, 1)
gmsh.model.geo.addLine(2, 3, 2)
gmsh.model.geo.addLine(3, 4, 3)
# try automatic assignement of tag
line4 = gmsh.model.geo.addLine(4, 1)
gmsh.model.geo.addCurveLoop([1, 2, 3, line4], 1)
gmsh.model.geo.addPlaneSurface([1], 6)
gmsh.model.geo.synchronize()
gmsh.model.mesh.generate(2)
gmsh.write("square_testing_gmsh_python.msh")
# gmsh.finalize()


In [ ]:
mesh = gmsh_api.Mesh.from_gmsh(gmsh)

In [ ]:
mesh.nodes

In [ ]:
ls

In [ ]:
mesh=gmsh_api.Mesh.from_gmsh("mesh_simple_square.msh")

In [ ]:
import meshio

In [ ]:
ls

In [ ]:
mesh = meshio.read("mesh_simple_square.msh")

In [ ]:
mesh.

In [ ]:
mesh = gmsh.model.mesh
vtags,vxyz,_ = mesh.getNodes()

In [ ]:
ls

In [ ]:
gmsh.open("mesh_simple_square.geo")

In [ ]:
gmsh.model.mesh.getElements()

In [ ]:
gmsh.finalize()

In [ ]:
pts.reshape((pts.size//3,3))

In [ ]:
type(mesh.elements.values)

In [ ]:
type(mesh.nodes["x"])

In [ ]:
import pyvista as pv

mesh = pv.read("square_testing_gmsh_python.msh")

In [ ]:
view(geometries=mesh)

In [ ]:
p = pv.Plotter()
p.add_mesh(mesh)
p.show()

In [1]:
# pip install gmsh-sdk gmsh-api
import gmsh
import gmsh_api


In [2]:
gmsh.initialize()

In [3]:
gmsh.open("mesh_simple_square.geo")

In [4]:
mesh = gmsh.model.mesh

In [6]:
tags, coord, _ = mesh.getNodes()

In [7]:
tags

array([   1,    2,    3, ..., 3719, 3720, 3721], dtype=uint64)

In [8]:
coord = coord.reshape((coord.size//3,3))

In [9]:
coord

array([[-0.5       ,  0.5       ,  0.        ],
       [-0.5       , -0.5       ,  0.        ],
       [ 0.5       ,  0.5       ,  0.        ],
       ...,
       [ 0.45      , -0.48333333,  0.        ],
       [ 0.46666667, -0.48333333,  0.        ],
       [ 0.48333333, -0.48333333,  0.        ]])

In [34]:
gmsh.model.getPhysicalName(*gmsh.model.getPhysicalGroups()[5])

'fluid'

In [35]:
a = (3,"hello",3.8)

In [40]:
print(*a)

3 hello 3.8


In [41]:
print( 3, "hello", 3.8 )

3 hello 3.8


In [47]:
print(*gmsh.model.getPhysicalGroups()[0])

0 200


In [43]:
gmsh.model.getPhysicalName()

TypeError: getPhysicalName() missing 2 required positional arguments: 'dim' and 'tag'

In [ ]:
import pyvista as pv
